[test]
preload = ["./test-setup.ts"]
coverage = true
coverageDir = "./coverage"
testMatch = ["**/*.test.ts", "**/*.test.tsx"]
exclude = ["node_modules", ".next", "coverage", "dist"]

[install.scopes]

[run]
